# Generated by Django 3.0.5 on 2020-05-25 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('owner_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('member', models.ManyToManyField(blank=True, related_name='a_group', to=settings.AUTH_USER_MODEL)),
                ('owner_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_group', to='contenttypes.ContentType')),
            ],
        ),
    ]
