# Generated by Django 3.0.5 on 2020-05-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
