# Generated by Django 3.0.5 on 2020-05-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='owner_ct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_group', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='owner_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
