# Generated by Django 3.0.5 on 2020-05-25 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('groups', '0002_auto_20200524_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='owner_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_group', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='owner_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
