# Generated by Django 3.0.5 on 2020-06-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_membersrequested'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupe',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='groupe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2020-06-10'),
            preserve_default=False,
        ),
    ]
