# Generated by Django 3.0.5 on 2020-06-10 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20200610_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersrequested',
            name='groupe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groups.Groupe'),
        ),
    ]
