# Generated by Django 3.0.5 on 2020-06-10 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0006_auto_20200610_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersrequested',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups_requested', related_query_name='groups_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PostRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groupe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groups.Groupe')),
            ],
        ),
    ]
