# Generated by Django 3.0.5 on 2020-06-13 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quans', '0004_auto_20200608_0718'),
        ('groups', '0007_auto_20200610_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionRequestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groups.Groupe')),
                ('questions', models.ManyToManyField(related_name='groups_request', to='quans.Question')),
            ],
        ),
        migrations.DeleteModel(
            name='PostRequest',
        ),
    ]
