# Generated by Django 3.0.5 on 2020-06-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quans', '0004_auto_20200608_0718'),
        ('groups', '0008_auto_20200613_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionrequestlist',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='groups_request', related_query_name='groups_request', to='quans.Question'),
        ),
    ]
