# Generated by Django 3.0.5 on 2020-05-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='sanix', max_length=50),
            preserve_default=False,
        ),
    ]
