# Generated by Django 3.0.7 on 2020-07-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-likes',)},
        ),
    ]
