# Generated by Django 3.0.5 on 2020-04-27 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='upvotes',
        ),
    ]
