# Generated by Django 3.0.5 on 2020-05-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200527_1852'),
        ('quans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='groups.Groupe'),
        ),
    ]
