# Generated by Django 3.0.5 on 2020-04-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quans', '0002_remove_question_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='no title added', max_length=80),
        ),
    ]
