# Generated by Django 3.0.5 on 2020-06-08 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quans', '0003_question_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='replies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_replies', to='quans.Answer'),
        ),
    ]
