# Generated by Django 3.0.5 on 2020-04-27 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quans', '0003_question_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('replies', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quans.Answer')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quans.Question')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
