# Generated by Django 3.0.5 on 2020-04-27 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quans', '0004_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='replies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quans.Answer'),
        ),
    ]
