# Generated by Django 3.0.5 on 2020-04-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quans', '0005_auto_20200427_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='reply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quans.Question'),
        ),
    ]
