# Generated by Django 3.0.5 on 2020-04-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quans', '0006_auto_20200427_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-submitted_on',)},
        ),
    ]
