# Generated by Django 3.0.5 on 2020-04-28 23:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quans', '0010_auto_20200428_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_upvote',
            field=models.ManyToManyField(related_name='answers_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
