# Generated by Django 3.0.5 on 2020-04-28 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quans', '0011_auto_20200428_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
